Plugins sort in admin uses incorrect callback; From issue #418
Loading up admin throws following error:

  Fatal error: Cannot call method self::strnatcmpCustom()
   or method does not exist in
   \oc-includes\osclass\classes\Plugins.php on line 114

Need to drop self:: or just remove quotes when called by uasort